GET http://localhost:3000/api/todos

###
POST http://localhost:3000/api/todos
Content-Type: application/json

{
  "label": "complete todo"
}

###

PUT http://localhost:3000/api/todos/8ef34a9e-24c4-414d-80d6-c4c40bad7d3b
Content-Type: application/json

{
  "label": "Finish learning Rust and leptos",
  "completed": true
}

###
DELETE http://localhost:3000/api/todos/7a1c0e63-8efc-4b68-802e-795421bb5b9b

###
GET http://localhost:3000/api/todos/7a1c0e63-8efc-4b68-802e-795421bb5b9b
Content-Type: application/json